### ISSUE TITLE
Special Session: Everything

### ISSUE THREAD

**Issue by cbas** [ga-students/wdi-sg-discussions#9]
Talk: **Everything I’ve learned in 15 years of software development that will still be relevant for the next 15 years**

Speaker: @gabehollombe
Date: 2016-01-08
Time: 12:00
Duration: 1 hour (lunch talk)

**Comment by cbas** [comment]
@gabehollombe How about the second week of 2016? That's Mon 4th Jan through Fri 8th Jan. We're flexible and can do a lunch talk (12:00-1:00pm for example) or choose a time slot in the morning/afternoon as best fits your schedule. The class is 9:00am to 5:00pm, Mon-Fri excluding public holidays.

**Comment by gabehollombe** [comment]
@cbas A lunch talk that week should work for me.  How about Friday the 8th at 12pm? You're at General Assembly just down the road from me (I'm on Craig road), right?

**Comment by cbas** [comment]
Wonderful! Sounds good for 8th. :+1: 

Yup, like 5 minute walk through the park. Side entrance to The Working Capitol.

**Comment by gabehollombe** [comment]
Woot! Scheduled.

**Comment by ongmin** [comment]
:open_mouth: This sounds so epic! Looking forward to it.

(sorry, I'm peeping around :see_no_evil:)

**Comment by cbas** [comment]
Knowing Gabe, it will be epic... FYI he's the man whose talk.js demos led to us learning Phaser.js :space_invader:

**Comment by gabehollombe** [comment]
*blush*

**Comment by caalberts** [comment]
Thanks for sharing! @gabehollombe

**Comment by cbas** [comment]
@gabehollombe The feedback on your talk was: **Epic!**

Have also added you to our little public chatroom: https://gitter.im/ga-students/wdi-sg-discussions (do you have out in the [SingaporeJS Gitter chatroom](https://gitter.im/SingaporeJS/discussions)?)

**Comment by jsstrn** [comment]
@gabehollombe Epic! Thanks for taking the time to speak to us!

**Comment by jerrygraced** [comment]
Notes that I took down from the session: https://github.com/jerrygraced/scratchpad/blob/master/special-session.md.  

Thanks @gabehollombe for the awesome sharing!

**Comment by ongmin** [comment]
I'm so bummed that I missed this. So taking the flu jab every year now. Bummer. :(

**Comment by gabehollombe** [comment]
My own notes from this talk:


Always Be Learning

Learning isn’t reading hacker news, blog posts, videos.  That’s step one.
Learning is writing code and finishing projects.  Going down a path, seeing
how it curves, what solution you end up with, reflecting, trying a
different approach.

Read the docs!  Language docs.  Library docs.  Framework docs.

Spend ten or twenty minutes getting an overview of the lay of the land
before you start using a new library or tool.  Don’t just find that first
code snippet example in the Quick Start guide, copy/paste it, and move on.
Without the bigger picture, you’re going to limit your interactions with
this code to what you’ve seen in a few tiny examples meant to demonstrate
the value of the thing but not teach you how to use it.

Don’t be afraid to read the source.  It’s just code.  It’s not magic.  It
was written by a human. You may not understand all of it, but you will
learn something every time you read someone else’s code.

Also dedicate time to your tools:

   -

   Shell
   -

   Editor
   -

   Language
   -

   Typing speed







Coding

Avoid analysis paralysis. Write shitty code that works, then make it
better. Give yourself permission to write crappy code in your first draft.

Practice Wish Driven Development - Go write the client code that uses a
class/function first (hopefully in an automated test), pretend it works.
Then go make that interface work.

Tony Hoare said: "There are two ways of constructing a software design: One
way is to make it so simple that there are obviously no deficiencies, and
the other way is to make it so complicated that there are no obvious
deficiencies. The first method is far more difficult."


Testing

If you don’t know where you’re trying to get to, don’t do TDD. Start with a
spike to figure out more of how the dots connect.

TDD is great, but think about your system before writing the tests. Make
sure you’re testing the right things - see The Magic Tricks of Testing by
Sandi Metz. Actually, see everything ever by Sandi.

Listen to your tests. If you’re not sure how to test part of your system,
or the test setup is painful, you should probably refactor your system.



Debugging

Answer the question ‘What happened’ with something more useful than ‘it
didn’t work’.

Read the stack trace / error mesage!  Seriously.  Even if you think you
know what line it’s failing on.  Make this a habit.  Otherwise, you will
sometimes incorrectly assume that you know what the problem is and waste a
lot of time thinking about and debugging the wrong thing.
http://www.informit.com/articles/article.aspx?p=1919440

Use the scientific method! Debugging is more scientific than Science! -
Stuart Sierra, Clojure Conj 2015.  Form a hypothesis and test it! Rinse,
repeat.


Keep your Ego in Check

When you look at some code and think “This is shit.”  Stop.  How can you be
accurate in that assumption when you just met it?  It’s possible you don’t
understand it all yet.  Code that’s rough around the edges probably means
it’s robust and handles edge cases you’re not thinking of.

It’s much, MUCH easier to critique something than to create it.

Saying “I don’t know” and “I don’t understand” is a good thing.  It’s
great. It’s essential.  It doesn’t mean “I’m stupid” or “I’m inexperienced
and not worth talking to about this.”  It means that you’re opening
yourself up to learning or understanding it.  I’ve learned enough to know
how much I don’t know.  When I was starting out, I thought I knew so much.


The Language Doesn’t Really Matter

You are not a ruby programmer.  You are not a rails programmer.  You are a
programmer.  Ruby / Rails are tools that you’re using today.  They likely
won’t be what you use ten years from now.

Don’t dismiss what someone is doing just because it’s not in a language /
framework that’s new cool thing you’re excited about.  Java doesn’t suck.
Perl doesn’t suck.  PHP doesn’t suck.  They all have purpose, value, and
plenty of smart people who do great things with them.


Create value for your business

Programmer time vs Execution time.  Both are valuable, keep both in mind.

Releasing something that works, even if it doesn’t do everything you need,
is infinitely better than not releasing because it’s not ready yet, doesn’t
have feature X.

Your job is not to write code.  Your job is to create value for the
business.
